// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listSubscriptions: () => typedError<Subscription[], string>(__TAURI_INVOKE("list_subscriptions")),
	createSubscription: (input: NewSubscription) => typedError<Subscription, string>(__TAURI_INVOKE("create_subscription", { input })),
	updateSubscription: (sub: Subscription) => typedError<null, string>(__TAURI_INVOKE("update_subscription", { sub })),
	deleteSubscription: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_subscription", { id })),
	listPaymentMethods: () => typedError<PaymentMethod[], string>(__TAURI_INVOKE("list_payment_methods")),
	createPaymentMethod: (input: NewPaymentMethod) => typedError<PaymentMethod, string>(__TAURI_INVOKE("create_payment_method", { input })),
	updatePaymentMethod: (pm: PaymentMethod) => typedError<null, string>(__TAURI_INVOKE("update_payment_method", { pm })),
	deletePaymentMethod: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_payment_method", { id })),
	listCategories: () => typedError<Category[], string>(__TAURI_INVOKE("list_categories")),
	createCategory: (input: NewCategory) => typedError<Category, string>(__TAURI_INVOKE("create_category", { input })),
	updateCategory: (cat: Category) => typedError<null, string>(__TAURI_INVOKE("update_category", { cat })),
	deleteCategory: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_category", { id })),
	getLlmConfig: () => typedError<{ provider: "claude"; api_key: string; model: string } | { provider: "openai"; api_key: string; model: string } | { provider: "gemini"; api_key: string; model: string } | { provider: "ollama"; endpoint: string; model: string } | { provider: "lmstudio"; endpoint: string; model: string } | null, string>(__TAURI_INVOKE("get_llm_config")),
	setLlmConfig: (config: LlmConfig) => typedError<null, string>(__TAURI_INVOKE("set_llm_config", { config })),
	extractSubscriptionFromText: (text: string) => typedError<ParsedSubscriptionHint, string>(__TAURI_INVOKE("extract_subscription_from_text", { text })),
	importCsvText: (text: string) => typedError<number, string>(__TAURI_INVOKE("import_csv_text", { text })),
	listDetectionEvents: () => typedError<DetectionEvent[], string>(__TAURI_INVOKE("list_detection_events")),
	confirmDetectionEvent: (id: string) => typedError<Subscription, string>(__TAURI_INVOKE("confirm_detection_event", { id })),
	confirmDetectionEventWithOverrides: (id: string, sub: NewSubscription) => typedError<Subscription, string>(__TAURI_INVOKE("confirm_detection_event_with_overrides", { id, sub })),
	rejectDetectionEvent: (id: string) => typedError<null, string>(__TAURI_INVOKE("reject_detection_event", { id })),
	/**
	 *  Reject a batch of pending detection events in one round-trip. Each id is
	 *  processed independently — same as calling `reject_detection_event` per id,
	 *  including sender → blocklist learning. Returns the count actually rejected.
	 */
	bulkRejectDetectionEvents: (ids: string[]) => typedError<number, string>(__TAURI_INVOKE("bulk_reject_detection_events", { ids })),
	listLearnedSenders: () => typedError<LearnedSender[], string>(__TAURI_INVOKE("list_learned_senders")),
	deleteLearnedSender: (sender: string) => typedError<null, string>(__TAURI_INVOKE("delete_learned_sender", { sender })),
	refreshExchangeRates: (base: string) => typedError<number, string>(__TAURI_INVOKE("refresh_exchange_rates", { base })),
	listExchangeRates: (base: string) => typedError<ExchangeRate[], string>(__TAURI_INVOKE("list_exchange_rates", { base })),
	getDefaultCurrency: () => typedError<string | null, string>(__TAURI_INVOKE("get_default_currency")),
	setDefaultCurrency: (currency: string) => typedError<null, string>(__TAURI_INVOKE("set_default_currency", { currency })),
	getUserLocale: () => typedError<string | null, string>(__TAURI_INVOKE("get_user_locale")),
	setUserLocale: (locale: string) => typedError<null, string>(__TAURI_INVOKE("set_user_locale", { locale })),
	getTranslations: (locale: string) => typedError<{ [key in string]: string } | null, string>(__TAURI_INVOKE("get_translations", { locale })),
	saveTranslations: (locale: string, translations: { [key in string]: string }) => typedError<null, string>(__TAURI_INVOKE("save_translations", { locale, translations })),
	/**
	 *  Translate a batch of English strings to `target_locale` using the user's
	 *  configured LLM provider. Returns a map of same keys → translated values.
	 *  Placeholder tokens (`{name}`, `{count}`, etc.) must be preserved by the LLM.
	 */
	translateStrings: (targetLocale: string, strings: { [key in string]: string }) => typedError<{ [key in string]: string }, string>(__TAURI_INVOKE("translate_strings", { targetLocale, strings })),
	exportSubscriptionsIcs: () => typedError<string, string>(__TAURI_INVOKE("export_subscriptions_ics")),
	saveGmailOauthCredentials: (creds: OAuthCredentials) => typedError<null, string>(__TAURI_INVOKE("save_gmail_oauth_credentials", { creds })),
	getGmailOauthCredentials: () => typedError<{
	client_id: string,
	client_secret: string,
} | null, string>(__TAURI_INVOKE("get_gmail_oauth_credentials")),
	hasGmailTokens: () => typedError<boolean, string>(__TAURI_INVOKE("has_gmail_tokens")),
	disconnectGmail: () => typedError<null, string>(__TAURI_INVOKE("disconnect_gmail")),
	/**
	 *  Abort any in-flight OAuth flow (Gmail or PayPal) so the UI can reset its
	 *  connecting state without waiting for the 2-minute timeout to fire.
	 */
	cancelOauth: () => typedError<null, string>(__TAURI_INVOKE("cancel_oauth")),
	/**
	 *  Cooperatively cancel an in-flight `run_gmail_scan` loop. The loop checks
	 *  the flag between messages and bails out with `scan cancelled`.
	 */
	cancelScan: () => typedError<null, string>(__TAURI_INVOKE("cancel_scan")),
	/**
	 *  Open the URL in the user's default browser (used by the error-dialog
	 *  action buttons that link to Google Cloud Console etc.).
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	startGmailOauth: () => typedError<null, string>(__TAURI_INVOKE("start_gmail_oauth")),
	runGmailScan: (range: YearMonthDto[]) => typedError<number, string>(__TAURI_INVOKE("run_gmail_scan", { range })),
	/**
	 *  Stage 2 — broader Gmail keywords plus a multi-month recurrence filter.
	 *  Only senders that appear in the selected range across 2+ distinct months
	 *  proceed to the LLM. Use after Stage 1 if you suspect it missed real
	 *  subscriptions hiding under non-tight keywords (Adobe Receipt, JR定期 etc.).
	 */
	runGmailDeepScan: (range: YearMonthDto[]) => typedError<number, string>(__TAURI_INVOKE("run_gmail_deep_scan", { range })),
	savePaypalOauthCredentials: (creds: OAuthCredentials) => typedError<null, string>(__TAURI_INVOKE("save_paypal_oauth_credentials", { creds })),
	getPaypalOauthCredentials: () => typedError<{
	client_id: string,
	client_secret: string,
} | null, string>(__TAURI_INVOKE("get_paypal_oauth_credentials")),
	hasPaypalTokens: () => typedError<boolean, string>(__TAURI_INVOKE("has_paypal_tokens")),
	disconnectPaypal: () => typedError<null, string>(__TAURI_INVOKE("disconnect_paypal")),
	startPaypalOauth: () => typedError<null, string>(__TAURI_INVOKE("start_paypal_oauth")),
	checkRenewalsNow: () => typedError<number, string>(__TAURI_INVOKE("check_renewals_now")),
};

/* Types */
export type BillingCycle = "weekly" | "monthly" | "quarterly" | "semi_annual" | "annual" | "custom";

export type Category = {
	id: string,
	name: string,
	icon: string | null,
	color: string | null,
	created_at: string,
	updated_at: string,
};

/**
 *  A piece of evidence — usually a parsed email or PayPal subscription record —
 *  that may correspond to a subscription. Sits in a review queue until the user
 *  confirms or rejects.
 * 
 *  Stored separately from `Subscription` so the user can audit and correct the
 *  extraction pipeline.
 */
export type DetectionEvent = {
	id: string,
	source: DetectionSource,
	// Stable external reference, e.g. Gmail message-id. Full message body is never stored.
	source_ref: string | null,
	raw_summary: string | null,
	/**
	 *  Normalized sender (lowercased email) for sender-learning. Optional
	 *  because not every source has a sender concept (e.g. manual / csv).
	 */
	sender: string | null,
	/**
	 *  Persisted as free JSON at the DB layer, but the extraction pipeline only
	 *  ever stores a serialized [`ParsedSubscriptionHint`]. Tell specta to emit
	 *  that concrete shape so the generated TS binding is fully typed instead of
	 *  a raw `serde_json::Value` union the frontend can't consume.
	 */
	parsed_payload: ParsedSubscriptionHint,
	confidence: number,
	status: DetectionStatus,
	matched_subscription_id: string | null,
	reviewed_at: string | null,
	created_at: string,
};

export type DetectionSource = "gmail" | "paypal" | "csv_import" | "manual";

export type DetectionStatus = "pending" | "confirmed" | "rejected" | "duplicate";

export type ExchangeRate = {
	base: string,
	quote: string,
	rate: number,
	fetched_at: string,
};

export type LearnedDecision = "allow" | "block";

export type LearnedSender = {
	sender: string,
	decision: LearnedDecision,
	updated_at: string,
};

export type LlmConfig = { provider: "claude"; api_key: string; model: string } | { provider: "openai"; api_key: string; model: string } | { provider: "gemini"; api_key: string; model: string } | { provider: "ollama"; endpoint: string; model: string } | { provider: "lmstudio"; endpoint: string; model: string };

// Input DTO for creating a category. The server fills in `id` and timestamps.
export type NewCategory = {
	name: string,
	icon: string | null,
	color: string | null,
};

// Input DTO for creating a payment method. The server fills in `id` and timestamps.
export type NewPaymentMethod = {
	name: string,
	kind: PaymentMethodKind,
	last4: string | null,
	color: string | null,
	icon: string | null,
};

// Input DTO for creating a subscription. The server fills in `id` and timestamps.
export type NewSubscription = {
	name: string,
	service_icon: string | null,
	plan: string | null,
	amount_minor: number,
	currency: string,
	billing_cycle: BillingCycle,
	next_billing_date: string | null,
	started_at: string | null,
	payment_method_id: string | null,
	category_id: string | null,
	status: SubscriptionStatus | null,
	notes: string | null,
};

export type OAuthCredentials = {
	client_id: string,
	client_secret: string,
};

/**
 *  Structured output of the extraction pipeline. Every field is optional because
 *  real-world receipts vary widely in what they expose.
 */
export type ParsedSubscriptionHint = {
	service_name: string | null,
	amount_minor: number | null,
	currency: string | null,
	billing_cycle: BillingCycle | null,
	payment_method_hint: string | null,
	charged_at: string | null,
};

export type PaymentMethod = {
	id: string,
	name: string,
	kind: PaymentMethodKind,
	last4: string | null,
	color: string | null,
	icon: string | null,
	created_at: string,
	updated_at: string,
};

export type PaymentMethodKind = "credit_card" | "debit_card" | "bank_account" | "paypal" | 
// Carrier billing (e.g. d-barai, au PAY, SoftBank "Matomete Shiharai").
"carrier" | 
// QR / mobile wallets (e.g. PayPay, Rakuten Pay, LINE Pay).
"wallet" | "app_store" | "play_store" | "crypto" | "other";

export type Subscription = {
	id: string,
	name: string,
	service_icon: string | null,
	plan: string | null,
	// Amount in minor units of `currency` (e.g. yen, cents). Avoids float drift.
	amount_minor: number,
	// ISO 4217 code, e.g. "JPY", "USD".
	currency: string,
	billing_cycle: BillingCycle,
	next_billing_date: string | null,
	started_at: string | null,
	payment_method_id: string | null,
	category_id: string | null,
	status: SubscriptionStatus,
	notes: string | null,
	created_at: string,
	updated_at: string,
};

export type SubscriptionStatus = "active" | "trial" | "paused" | "cancelled";

export type YearMonthDto = {
	year: number,
	month: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

